# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 24.4.2 # Use the version of black you have in pyproject.toml or latest
    hooks:
    -   id: black
        args: [--line-length=88]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Use the version of isort you have or latest
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Use the version of flake8 you have or latest
    hooks:
    -   id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,W503,E501']
        # additional_dependencies: [flake8-docstrings, ...] # Add any flake8 plugins if you use them
